# Generated by Django 6.1 on 2026-09-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabalho', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anotacao',
            options={'verbose_name': 'Anotação', 'verbose_name_plural': 'Anotações'},
        ),
    ]
